video_file: ./test-example/2025-12-20_17-59-46.mkv
output_dir: ./output_phase3_3chunk
mode: production

demo_duration_sec: 60
fragment_size_min: 1
max_video_duration_sec: 190

whisper_model: tiny
device: cpu
language: ru
initial_prompt: "Russian and Ukrainian speech. Do not translate. Transcribe verbatim."
beam_size: 1
vad_filter: true

preferred_stream_index: 1
s1_channel: FL
s2_channel: FR
enable_channel_prescan: false
prescan_duration_sec: 8

audio_bitrate: 128k
min_text_len: 2
